# Structured recipe cards for Odia dishes (used by scripts/add-recipes.py).
# Quantities are typical home amounts; methods are written by Odiapedia from several published recipes (see each article's sources).

RECIPES = {
"dalma": dict(yield_="4–6 servings", prep=20, cook=30, course="Main course", diet=["Vegetarian"], ingredients=[
    "1 cup toor (arhar) dal, washed and soaked 20 minutes",
    "3½–4 cups water",
    "2½–3 cups mixed vegetables in 1-inch pieces: raw papaya, raw banana, pumpkin, brinjal, a small potato, drumstick or pointed gourd",
    "½ tsp turmeric and salt to taste",
    "1-inch piece ginger, grated",
    "2 tbsp ghee (or mustard oil)",
    "1 tsp panch phutana",
    "2 dried red chillies and 1 bay leaf",
    "2 green chillies, slit",
    "Bhaja masala: 1 tsp cumin seeds and 2 dried red chillies, dry-roasted and ground",
    "2 tbsp grated coconut and coriander leaves to finish",
], steps=[
    "Cook the dal with the water, turmeric and ginger until soft but not completely broken down — about two whistles in a pressure cooker or 15–20 minutes in an open pot.",
    "Add the firm vegetables (papaya, banana, potato, drumstick) with salt and cook 5 minutes, then add the soft ones (pumpkin, brinjal). Simmer until tender but still holding their shape; dalma should be thick and pourable.",
    "Heat the ghee in a small pan; add the bay leaf, red chillies and panch phutana and let the mustard seeds pop without burning. Add the green chillies.",
    "Pour the tempering over the dal and cover for a minute so it infuses.",
    "Stir in the roasted cumin–chilli powder, then finish with coconut, coriander and a spoon of ghee. Serve hot with rice.",
], tips=[
    "For the temple-style (satvik) version, cook without onion or garlic and temper only in ghee.",
    "Roast and grind the bhaja masala fresh — its smoky note is what makes dalma taste Odia.",
]),
"pakhala-bhata": dict(yield_="4 servings", prep=10, cook=20, rest=480, rest_label="Fermenting (basi pakhala)", course="Main course", diet=["Vegetarian"], ingredients=[
    "2 cups cooked rice (about 1 cup raw), cooled",
    "4–5 cups drinking water at room temperature",
    "½–¾ cup plain curd, whisked (for dahi pakhala)",
    "Salt to taste",
    "1 tbsp oil, 1 tsp mustard seeds, 1 tsp cumin, 8–10 curry leaves, 1–2 dried red chillies",
    "1 tsp roasted cumin powder",
    "To serve: green chillies, onion, lime and sides such as alu bhaja, baigana poda, badi chura, saga bhaja or fried fish",
], steps=[
    "For basi pakhala, cover the cooled rice with water in a pot, cover loosely and leave overnight at room temperature until faintly sour. For saja pakhala use freshly cooled rice.",
    "Squeeze the rice lightly with your fingers, then stir in salt and curd (or lemon for saja pakhala). Add water until it is loose and soupy.",
    "Heat the oil, splutter the mustard seeds, cumin, red chillies and curry leaves, and pour the tempering over the rice.",
    "Stir in the roasted cumin. Serve at room temperature with fried and roasted sides.",
], tips=[
    "In hot weather 6–8 hours of fermenting is usually enough.",
    "The plainest pakhala is just rice, water, salt and a green chilli.",
]),
"chhena-poda": dict(yield_="6–8 servings", prep=30, cook=70, rest=60, rest_label="Hanging the chhena", course="Dessert", diet=["Vegetarian"], ingredients=[
    "Chhena (fresh cheese) from 2 litres full-fat milk, about 400 g, hung until just moist",
    "⅔ cup sugar (or grated jaggery)",
    "2 tbsp fine semolina",
    "½ tsp cardamom powder",
    "2 tbsp ghee, plus extra for greasing",
    "10–12 cashews and 1 tbsp raisins",
    "2–3 tbsp milk, only if the mixture is crumbly",
    "A sal or banana leaf to line the tin (optional, traditional)",
], steps=[
    "Knead the crumbled chhena with the heel of your hand for 5–8 minutes until smooth.",
    "Mix in the sugar, semolina, cardamom, ghee, cashews and raisins and rest 15–20 minutes so the semolina softens. It should be like a thick cake batter.",
    "Grease a round tin, line it with the leaf if using, and spread in the mixture.",
    "Bake at 180–190 °C for 60–75 minutes, until the top and edges are deep brown and a skewer comes out clean.",
    "Cool completely in the tin — it firms as it cools — then slice into wedges.",
], tips=[
    "Jaggery gives the darker flavour of many roadside sweet shops.",
    "Without an oven, bake in a heavy covered pan on a bed of salt over low heat for about an hour.",
]),
"santula": dict(yield_="4 servings", prep=15, cook=20, course="Side dish", diet=["Vegetarian"], ingredients=[
    "3 cups mixed vegetables in even cubes: raw papaya, potato, brinjal, ridge gourd, pumpkin, raw banana or drumstick",
    "½ tsp turmeric and salt to taste",
    "1 tbsp mustard oil or ghee",
    "½ tsp panch phutana",
    "1 dried red chilli and 2 green chillies, slit",
    "3–4 garlic cloves and ½-inch ginger (leave out for a satvik version)",
    "¼ cup milk (for dudha santula, optional)",
    "Coriander leaves",
], steps=[
    "Boil the vegetables in a little salted water with turmeric until just tender, adding the soft vegetables a few minutes after the firm ones. Keep the cooking water.",
    "Heat the oil, crackle the panch phutana and red chilli, then add garlic, ginger and green chillies.",
    "Add the drained vegetables and toss gently for 2–3 minutes, adding a splash of the cooking water if dry.",
    "For dudha santula, add the milk and simmer 2–3 minutes until creamy. Garnish with coriander.",
], tips=[
    "Bhaja santula: sauté the raw vegetables in the tempering, then add a little water, cover and cook.",
    "Cut everything to the same size so nothing turns to mush.",
]),
"machha-besara": dict(yield_="4 servings", prep=20, cook=30, course="Main course", diet=[], ingredients=[
    "500 g rohu or catla steaks",
    "½ tsp turmeric and ½ tsp salt for the fish",
    "Mustard paste: 2 tbsp mustard seeds (soaked 15 minutes), 4–5 garlic cloves, 2 green chillies, a pinch of salt",
    "4 tbsp mustard oil",
    "½ tsp panch phutana",
    "1 tomato, chopped (optional)",
    "½ tsp each turmeric, red chilli powder and coriander powder",
    "2 pieces ambula (sun-dried mango) or 1 tsp tamarind pulp",
    "1 cup water, salt, coriander leaves",
], steps=[
    "Rub the fish with turmeric and salt. Heat the mustard oil until it just smokes, lower the heat and fry the fish golden on both sides; set aside.",
    "Grind the mustard, garlic, chillies and salt in short pulses with a few drops of water — over-grinding makes mustard bitter.",
    "In the same oil fry the panch phutana, then the tomato until soft, then the powdered spices.",
    "Add the mustard paste thinned with the water and simmer gently 10–15 minutes to mellow its raw sharpness.",
    "Add the fish and ambula and simmer 8–10 minutes, spooning the gravy over. Serve with rice.",
], tips=[
    "Many Odia homes leave out onion and tomato for a cleaner mustard flavour.",
    "The same gravy makes a vegetarian besara with pumpkin, raw banana or taro stems.",
]),
"chenna-jhilli": dict(yield_="About 20 pieces", prep=30, cook=40, rest=120, rest_label="Soaking in syrup", course="Dessert", diet=["Vegetarian"], ingredients=[
    "Chhena from 2 litres full-fat milk (about 400 g), well drained",
    "2–3 tbsp maida (plain flour)",
    "½ tsp cardamom powder and a tiny pinch of baking soda (optional)",
    "1 tbsp powdered sugar",
    "Syrup: 2 cups sugar, 2 cups water, 2–3 crushed cardamom pods, 1 bay leaf",
    "Ghee or oil for deep frying",
], steps=[
    "Simmer the syrup ingredients 8–10 minutes until slightly sticky, and keep warm.",
    "Knead the chhena 8–10 minutes until completely smooth, then work in the flour, sugar, cardamom and soda to a soft, crack-free dough.",
    "Shape small rings, coils or ovals.",
    "Fry in warm ghee over low heat so the inside cooks, then raise the heat slightly to colour them deep golden-red.",
    "Drop straight into the warm syrup and soak at least 2 hours.",
], tips=[
    "If the dough cracks, knead longer or add a teaspoon of milk.",
    "Oil that is too hot browns the outside and leaves the centre dense.",
]),
"rasabali": dict(yield_="About 12 pieces", prep=30, cook=60, rest=60, rest_label="Soaking in milk", course="Dessert", diet=["Vegetarian"], ingredients=[
    "Chhena from 1 litre full-fat milk (about 200 g), drained",
    "1 tbsp fine semolina and 1 tsp maida (optional)",
    "½ tsp cardamom powder, a pinch of baking soda, 1 tsp sugar",
    "Ghee for frying",
    "Thickened milk: 1.5 litres full-fat milk, ⅓–½ cup sugar, ½ tsp cardamom, a few saffron strands (optional)",
    "Chopped pistachios or almonds to garnish",
], steps=[
    "Simmer the milk in a wide heavy pan, scraping the sides, until reduced by half to two-thirds. Add sugar, cardamom and saffron and keep warm.",
    "Knead the chhena smooth, then knead in the semolina, flour, soda, sugar and cardamom.",
    "Divide into lime-sized balls and press each into a thin disc about 5–6 cm across.",
    "Fry the discs in ghee over medium-low heat until deep reddish-brown on both sides.",
    "Soak them in the warm thickened milk for at least an hour. Serve warm or chilled with nuts.",
], tips=[
    "The deep red-brown frying gives Kendrapara rasabali its colour and caramel note.",
    "Keep the milk pourable — it should not reduce to solid rabdi.",
]),
"dahi-baigana": dict(yield_="4 servings", prep=15, cook=15, course="Side dish", diet=["Vegetarian"], ingredients=[
    "250–300 g brinjal, sliced into rounds",
    "½ tsp turmeric, ½ tsp chilli powder, salt",
    "1½ cups thick curd, whisked",
    "1–2 tsp sugar and a pinch of black salt",
    "3 tbsp mustard oil",
    "1 tsp panch phutana",
    "1–2 dried red chillies, 1 green chilli, 8–10 curry leaves, ½-inch ginger",
    "½ tsp roasted cumin powder and coriander leaves",
], steps=[
    "Coat the brinjal slices with turmeric, chilli powder and salt and rest 10 minutes.",
    "Shallow-fry in 2 tbsp mustard oil until soft and browned on both sides; drain.",
    "Whisk the curd with sugar, black salt and a little salt, thinning with 2–3 tbsp water if very thick.",
    "Heat the remaining oil and crackle the panch phutana, chillies, curry leaves and ginger. Let the tempering cool a minute so it does not split the curd.",
    "Stir the tempering and brinjal into the curd, sprinkle with roasted cumin and coriander, and serve at room temperature.",
], tips=[
    "On festival days make it without onion or garlic; ghee can replace mustard oil.",
    "Add the brinjal just before serving if you like it with some bite.",
]),
"manda-pitha": dict(yield_="12–14 pithas", prep=30, cook=25, course="Dessert", diet=["Vegetarian"], ingredients=[
    "Dough: 1½ cups fine rice flour, 1½–1¾ cups water, ½ tsp salt, 1 tsp ghee",
    "Filling: 1½ cups grated fresh coconut, ¾ cup grated jaggery, ½ tsp cardamom, ¼ tsp crushed black pepper",
    "2 tbsp crumbled chhena (optional)",
    "Turmeric or banana leaves for steaming (optional)",
], steps=[
    "Cook the coconut and jaggery over medium heat, stirring, until thick (8–10 minutes). Add cardamom, pepper and chhena; cool.",
    "Boil the water with salt and ghee, lower the heat, add the rice flour at once and stir until absorbed. Cover 10 minutes, then knead smooth while warm.",
    "Shape lime-sized balls into thin cups, fill with a spoon of filling and seal into half-moons or domes.",
    "Steam on greased plates or leaves for 12–15 minutes until glossy and no longer sticky.",
], tips=[
    "Brush the shells with a little ghee so they don't crack while steaming.",
    "A spiced moong dal filling makes a savoury manda.",
]),
"arisa-pitha": dict(yield_="About 20 pithas", prep=60, cook=45, rest=300, rest_label="Soaking the rice", course="Dessert", diet=["Vegetarian"], ingredients=[
    "500 g short-grain raw rice",
    "400–500 g jaggery",
    "½ cup water for the syrup",
    "¼ cup white sesame seeds",
    "2 tbsp grated dry coconut (optional)",
    "A pinch of cardamom (or edible camphor) and salt",
    "Oil or ghee for deep frying",
], steps=[
    "Soak the rice 4–7 hours, drain and dry on a cloth until just damp.",
    "Grind or pound it to a fine flour while still slightly moist, and sieve.",
    "Boil the jaggery with the water to a one-string syrup.",
    "Lower the heat and add the flour gradually, stirring hard, until a thick glossy dough leaves the pan. Mix in coconut, cardamom and salt and cool until you can handle it.",
    "Shape lime-sized balls, press into sesame seeds and flatten to discs about 5 mm thick.",
    "Deep-fry over medium heat until golden-brown, then press each between two flat ladles to squeeze out excess oil. They crisp as they cool.",
], tips=[
    "Test one first: undercooked syrup makes pithas break up in the oil; overcooked syrup makes the dough hard.",
    "Stored airtight, arisa keeps for weeks.",
]),
"chingudi-malai": dict(yield_="4 servings", prep=20, cook=25, course="Main course", diet=[], ingredients=[
    "500 g prawns, shelled and deveined",
    "½ tsp turmeric and ½ tsp salt",
    "3 tbsp mustard oil (or oil and ghee)",
    "1 bay leaf, small cinnamon stick, 3–4 green cardamoms, 3–4 cloves",
    "1 onion, ground to a paste",
    "1 tsp ginger paste and ½ tsp garlic paste",
    "2–3 green chillies, ½ tsp red chilli powder (optional)",
    "1 cup thick and ½ cup thin coconut milk",
    "1 tsp sugar, salt, 1 tsp ghee",
], steps=[
    "Coat the prawns with turmeric and salt and sear in hot oil about a minute a side, just until they curl. Remove.",
    "Fry the whole spices in the same oil, then the onion paste until golden and the oil separates.",
    "Add ginger, garlic, chillies and chilli powder for 2 minutes, then the thin coconut milk; simmer 5 minutes.",
    "Lower the heat, add the thick coconut milk, sugar, salt and the prawns, and simmer gently 4–5 minutes without boiling hard.",
    "Finish with ghee and serve with rice.",
], tips=[
    "A spoon of mustard paste instead of coconut milk turns it into chingudi besara.",
    "Overcooked prawns turn rubbery — small ones need only 2–3 minutes.",
]),
"kanika": dict(yield_="3–4 servings", prep=10, cook=25, rest=30, rest_label="Soaking the rice", course="Main course", diet=["Vegetarian"], ingredients=[
    "1 cup short-grain aromatic rice (Gobindobhoga or similar)",
    "3–4 tbsp ghee",
    "¼ tsp turmeric and ½ tsp salt",
    "1 bay leaf, 1-inch cinnamon, 3 green cardamoms, 1 black cardamom, 4 cloves, a blade of mace, 6 peppercorns",
    "2 cups hot water",
    "¼ cup sugar, or to taste",
    "12 cashews and 1 tbsp raisins",
    "A pinch of nutmeg and ½ tsp grated ginger (optional)",
], steps=[
    "Soak the rice 30 minutes and drain. Rub in 1 tbsp ghee, the turmeric and salt and rest 20–30 minutes.",
    "Fry the cashews and raisins golden in the remaining ghee and lift out. Fry the whole spices 30 seconds in the same ghee.",
    "Add the rice and fry gently 2–3 minutes, then the hot water. Cover and cook on low until three-quarters done.",
    "Scatter the sugar over, cover and cook on the lowest heat 5–8 minutes until the water is absorbed.",
    "Fold in the nuts and nutmeg and rest covered 5 minutes. Serve with dalma.",
], tips=[
    "For bhoga style use only ghee and no onion or garlic.",
    "Adjust the sugar to taste; festive versions are sweeter.",
]),
"ghanta-tarkari": dict(yield_="6 servings", prep=30, cook=45, rest=480, rest_label="Soaking the legumes", course="Main course", diet=["Vegetarian"], ingredients=[
    "⅓ cup chana dal or dried chickpeas, soaked overnight; ¼ cup sprouted moong (optional)",
    "4–5 cups mixed vegetables: raw banana, pumpkin, sweet potato, taro, yam, brinjal, ridge gourd, papaya, beans, spine gourd, elephant apple (ou) if available",
    "½ tsp turmeric and salt",
    "3 tbsp mustard oil",
    "1 tsp panch phutana, 2 dried red chillies, 1 bay leaf",
    "1-inch ginger, ground",
    "Mustard paste: 1 tbsp mustard seeds and 2 green chillies ground with a little water",
    "Bhaja masala: 1 tsp cumin and 2 red chillies, roasted and ground",
    "¼ cup grated coconut and 1 tsp ghee",
], steps=[
    "Cook the soaked chana and moong until soft but whole.",
    "Par-boil the hard vegetables (yam, taro, sweet potato, raw banana) with turmeric and salt for 5–6 minutes; taro and yam must be cooked through.",
    "Heat the oil and fry the panch phutana, chillies and bay leaf, then the ginger.",
    "Add all the vegetables and fry 5 minutes; add the mustard paste, legumes and about 1½ cups water. Cover and simmer 15–20 minutes until thick and partly mashed.",
    "Stir in the bhaja masala and coconut and finish with ghee.",
], tips=[
    "The more kinds of vegetable, the better — use what is in season.",
    "Elephant apple gives the traditional sourness; a little tamarind can stand in.",
]),
"khechudi": dict(yield_="4 servings", prep=15, cook=35, course="Main course", diet=["Vegetarian"], ingredients=[
    "1 cup short-grain aromatic rice",
    "½ cup split yellow moong dal, dry-roasted",
    "5 cups water",
    "3 tbsp ghee",
    "1 bay leaf, 1 tsp cumin seeds, ¼ tsp asafoetida",
    "1 tsp grated ginger",
    "½ tsp turmeric, 1 tsp freshly ground black pepper, rock salt",
    "⅓ cup grated fresh coconut",
    "1 tsp jaggery or sugar",
], steps=[
    "Wash and soak the rice and dal together 15–20 minutes; drain.",
    "Boil the water, add rice, dal, turmeric, ginger and salt and simmer, partly covered, about 20 minutes.",
    "Add the coconut and pepper and cook on low 8–10 minutes until soft and porridge-like.",
    "Heat 2 tbsp ghee with the bay leaf, cumin and asafoetida and pour over.",
    "Stir in the jaggery and remaining ghee, rest 5 minutes and serve.",
], tips=[
    "Mitha khechudi, the sweet version, adds more ghee, sugar, cardamom and dry fruit.",
    "Keep it satvik for bhoga style: no onion, garlic, tomato or chilli.",
]),
}
